### ISSUE TITLE
add class for ranking based on CatBoost

### ISSUE THREAD

**Issue by MezentsevaAnastasia** [nsk-researchers/lingvoTerminator#4]
Recently [catboost](https://catboost.ai/en/docs/) become strong baseline in classification task. So it is quite relevant to make an experiment with it.
Also this instrument provides features for interpretation. It can become quite important in future development.

I suggest use this [class](https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier) for realisation. Docs are well-structured and it easy to use in any machine. 

TO DO: write a new class for ranking which must be inherited from `BaseCandidatesRanger` or maybe it is better to make an additional class for `GradientBoostingRanger` for all approaches based on gradient boosting, as you wish.

**Comment by ohsophie** [comment]
https://github.com/nsk-researchers/lingvoTerminator/pull/8
